name: natuurlijkegeneeskunde
favicon: null
layout_spectrum: 0.35507
typography_spectrum: 0.9897208465263247
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#b7c8dd'
    - '#000200'
    - '#405733'
    - '#fcfcfc'
    - '#7e8c57'
  brandStrength: 0.6522151145618409
  lightness: 0.5540497722104192
  saturation: 0.6401853624265641
  rhythmicContrast: 0.6428075316362083
purpose: []
