name: natuurlijkegeneeskunde
favicon: null
layout_spectrum: 0.29361
typography_spectrum: 0.89782
title: 'Praktijk Fontaine '
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#000000'
    - '#dfded9'
    - '#968e80'
    - '#82b200'
    - '#611804'
  brandStrength: 0.5625
  lightness: 0.5540497722104192
  saturation: 0.6401853624265641
  rhythmicContrast: 0.6428075316362083
purpose: []
