name: natuurlijkegeneeskunde
favicon: null
layout_spectrum: 0.2921902504749596
typography_spectrum: 0.9897208465263247
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#9D2D3C'
    - '#DDE4DD'
    - '#BCAB47'
    - '#6B574B'
    - '#160600'
  brandStrength: 0.6522151145618409
  lightness: 0.5540497722104192
  saturation: 0.6401853624265641
  rhythmicContrast: 0.6428075316362083
purpose: []
